### PR TITLE
Enhance Game List with Advanced Filtering Options

### LINKED ISSUE #87: Filter Library, Installed/Not installed filter
Sometimes, when you have a big library of games, it is problematic to find games that are already downloaded on your Mac. So, I suggest you adding a filter option in Library tab, to filter games by being installed, Windows/Mac, Epic/Steam/Local, (maybe) genre etc.

### PR DESCRIPTION
**Pull request by marcusziade**
Close #87 

This PR introduces advanced filtering capabilities to the GameListEvo view, improving user experience and game management. Key changes include:

1. Added a filter bar with options for installed games, platforms, and game sources.
2. Implemented FilterOptions struct to manage filter states.
3. Refactored game filtering and sorting logic for better performance and readability.
4. Updated localization strings to support new filter options.

https://github.com/MythicApp/Mythic/assets/47460844/53a29e3e-d870-4985-a6dc-2f61fc0446c6

### CODE REVIEW

**Comment by marcusziade** [comment]
There are other issues that mention the slow performance of this view. The slow downs are quite apparent during filtering. I'm gonna look more into multi-threading the code after we've worked through these UI improvements.

**Comment by blackxfiied** [comment]
@marcusziade Sure thing.
Thanks for this PR, sorting has been something I've planned on looking into 🙏🏾

**Comment by blackxfiied** [comment]
Instead of adding custom enumerations, it'd be more idea to use existing ones, e.g. `GamePlatform` instead of `Platform`, `GameType` instead of `Source`

**Comment by jeremybosma** [comment]
Maybe instead of having this non-optional bar at the top of the library at all times, a filter icon with a popover with these options would be better with some kind of indicator about if there are filters applied or not.

**Comment by marcusziade** [comment]
> @marcusziade Instead of adding custom enumerations, it'd be more idea to use existing ones, e.g. `GamePlatform` instead of `Platform`, `GameType` instead of `Source`.
> 
> I would do this myself, but I don't want to break your other open PRs. At the moment, this is preventing me from merging all of your other open PRs.
> 
> Sorry about that, especially doesn't help with the git oopsie I made earlier today.

If there are existing types, then let's definitely use those. I'll redo and reopen this 👍

**Comment by marcusziade** [comment]
> Maybe instead of having this non-optional bar at the top of the library at all times, a filter icon with a popover with these options would be better with some kind of indicator about if there are filters applied or not.

Would you draw a simple sketch for me? Sounds good, just need to confirm.

**Comment by blackxfiied** [comment]
@marcusziade 
You can create clean-looking dropdowns by using `Menu`s in `ZStack`s apparently

**Comment by jeremybosma** [comment]
> > Maybe instead of having this non-optional bar at the top of the library at all times, a filter icon with a popover with these options would be better with some kind of indicator about if there are filters applied or not.
> 
> Would you draw a simple sketch for me? Sounds good, just need to confirm, @jeremybosma

I was thinking a simple popover with apple themed stuff like
IMG_6383

i think this will look much better especially on the non maximized window. The entire interface should feel and utilize more things actually apple products do imo so it feels part of the operating system. Performance also plays a big role in this everywhere around the app.

**Pull request merged**
